makefile: move contrib directory check to contrib/Makefile
Signed-off-by: Steven Noonan <steven@uplinklabs.net>

diff --git a/crawl-ref/source/contrib/Makefile b/crawl-ref/source/contrib/Makefile
--- a/crawl-ref/source/contrib/Makefile
+++ b/crawl-ref/source/contrib/Makefile
@@ -12,7 +12,11 @@ clean distclean:
 	rm -rf $(PREFIX)
 
 $(SUBDIRS):
-	@cd $@; \
+	@if [ ! -x $@ ]; then \
+	    echo "The '$@' folder is missing. Have you run 'git submodule update --init'?"; \
+	    exit 1; \
+	fi
+	@cd $@ && \
 	$(MAKE) all prefix=$(PREFIX) && \
 	$(MAKE) install prefix=$(PREFIX)
 
