Revert "탭1칸을 들여쓰기4칸으로 변환"
This reverts commit 191b4b0923c21b7b87002f71b040e526b940c145.

diff --git a/crawl-ref/source/contrib/Makefile b/crawl-ref/source/contrib/Makefile
--- a/crawl-ref/source/contrib/Makefile
+++ b/crawl-ref/source/contrib/Makefile
@@ -10,38 +10,38 @@ SUBDIRS += lua/src
 endif
 
 all:
-    @$(MAKE) $(SUBDIRS)
+	@$(MAKE) $(SUBDIRS)
 
 clean distclean:
-    @for a in $(SUBDIRS); do \
-        $(MAKE) -C $$a distclean; \
-    done
-    rm -rf $(PREFIX)
+	@for a in $(SUBDIRS); do \
+	    $(MAKE) -C $$a distclean; \
+	done
+	rm -rf $(PREFIX)
 
 $(SUBDIRS):
-    @if [ ! -x $@ ]; then \
-        echo "**********************************************************"; \
-        echo; \
-        echo "The '$@' directory is missing. Have you run"; \
-        echo "   'git submodule update --init'?"; \
-        echo "(It's probably better to install all native dependencies instead.)"; \
-        echo; \
-        echo "**********************************************************"; \
-        exit 1; \
-    fi
-    @if [ ! -f $@/Makefile ] && [ ! -f $@/makefile ]; then \
-        echo "**********************************************************"; \
-        echo; \
-        echo "The '$@' directory exists, but the Makefile is missing!"; \
-        echo "Did 'git submodule update' work properly?"; \
-        echo "(It's probably better to install all native dependencies instead.)"; \
-        echo; \
-        echo "**********************************************************"; \
-        exit 1; \
-    fi
-    @cd $@ && \
-    $(MAKE) all prefix=$(shell echo $@ | perl -pe 's/[^\/]+/../g')/$(PREFIX)/$(ARCH) && \
-    $(MAKE) install prefix=$(shell echo $@ | perl -pe 's/[^\/]+/../g')/$(PREFIX)/$(ARCH)
+	@if [ ! -x $@ ]; then \
+	    echo "**********************************************************"; \
+	    echo; \
+	    echo "The '$@' directory is missing. Have you run"; \
+	    echo "   'git submodule update --init'?"; \
+	    echo "(It's probably better to install all native dependencies instead.)"; \
+	    echo; \
+	    echo "**********************************************************"; \
+	    exit 1; \
+	fi
+	@if [ ! -f $@/Makefile ] && [ ! -f $@/makefile ]; then \
+	    echo "**********************************************************"; \
+	    echo; \
+	    echo "The '$@' directory exists, but the Makefile is missing!"; \
+	    echo "Did 'git submodule update' work properly?"; \
+	    echo "(It's probably better to install all native dependencies instead.)"; \
+	    echo; \
+	    echo "**********************************************************"; \
+	    exit 1; \
+	fi
+	@cd $@ && \
+	$(MAKE) all prefix=$(shell echo $@ | perl -pe 's/[^\/]+/../g')/$(PREFIX)/$(ARCH) && \
+	$(MAKE) install prefix=$(shell echo $@ | perl -pe 's/[^\/]+/../g')/$(PREFIX)/$(ARCH)
 
 libpng freetype: zlib
 sdl2-image: sdl2 libpng
