contrib/Makefile: add check for Makefile existence in subdirs
Signed-off-by: Steven Noonan <steven@uplinklabs.net>

diff --git a/crawl-ref/source/contrib/Makefile b/crawl-ref/source/contrib/Makefile
--- a/crawl-ref/source/contrib/Makefile
+++ b/crawl-ref/source/contrib/Makefile
@@ -13,11 +13,21 @@ clean distclean:
 
 $(SUBDIRS):
 	@if [ ! -x $@ ]; then \
-	    echo "*******************************************************************************"; \
-		echo; \
-	    echo "The '$@' folder is missing. Have you run 'git submodule update --init'?"; \
-		echo; \
-	    echo "*******************************************************************************"; \
+	    echo "**********************************************************"; \
+	    echo; \
+	    echo "The '$@' folder is missing. Have you run"; \
+	    echo "   'git submodule update --init'?"; \
+	    echo; \
+	    echo "**********************************************************"; \
+	    exit 1; \
+	fi
+	@if [ ! -f $@/Makefile ] && [ ! -f $@/makefile ]; then \
+	    echo "**********************************************************"; \
+	    echo; \
+	    echo "The '$@' folder exists, but the Makefile is missing!"; \
+	    echo "Did 'git submodule update' work properly?"; \
+	    echo; \
+	    echo "**********************************************************"; \
 	    exit 1; \
 	fi
 	@cd $@ && \
